use_frameworks!

target 'CustomNavigationBar_Example' do
  pod 'CustomNavigationBar', :path => '../'

  target 'CustomNavigationBar_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
